const REJECTION_REASONS = Object.freeze({
  ACCEPTED: "ACCEPTED",
  BEST_LEVEL_SIZE_UNAVAILABLE: "BEST_LEVEL_SIZE_UNAVAILABLE",
  BEST_LEVEL_OVERCONSUMPTION: "BEST_LEVEL_OVERCONSUMPTION",
  DEPTH_INSUFFICIENT: "DEPTH_INSUFFICIENT",
  MAX_ORDER_TOTAL: "MAX_ORDER_TOTAL",
  MIN_ORDER_AMOUNT_NOT_MET: "MIN_ORDER_AMOUNT_NOT_MET",
  MIN_ORDER_TOTAL: "MIN_ORDER_TOTAL",
  OBSERVATION_SNAPSHOT_MISSING: "OBSERVATION_SNAPSHOT_MISSING",
  OBSERVATION_VALIDATION_SNAPSHOT_GAP: "OBSERVATION_VALIDATION_SNAPSHOT_GAP",
  ORDERBOOK_LEVEL_GROUPING_UNSUPPORTED: "ORDERBOOK_LEVEL_GROUPING_UNSUPPORTED",
  PROFIT_BELOW_THRESHOLD: "PROFIT_BELOW_THRESHOLD",
  STALE_ORDERBOOK: "STALE_ORDERBOOK",
  VALIDATION_DEPTH_UNIT_MISMATCH: "VALIDATION_DEPTH_UNIT_MISMATCH",
  VALIDATION_LEG_TIMESTAMP_SKEW: "VALIDATION_LEG_TIMESTAMP_SKEW",
  VALIDATION_RECEIVE_STALE: "VALIDATION_RECEIVE_STALE",
});

function rejectionReason(reason) {
  if (!reason) return null;
  return REJECTION_REASONS[reason] || String(reason);
}

module.exports = {
  REJECTION_REASONS,
  rejectionReason,
};
